// Ring Roads UI-kit sample data + bilingual strings. Registers on window.
window.RR_DATA = {
  properties: [
    { id: 1, code: 'A-101', icon: '🏠', status: 'available',
      address: { en: 'Sheikh Zayed, Giza', ar: 'الشيخ زايد، الجيزة' },
      price: 2500000, type: 'sale', beds: 3, baths: 2,
      finish: { en: 'Luxury', ar: 'فاخر' }, unit: { en: 'Apt 1', ar: 'شقة 1' },
      agent: { en: 'M. Ahmed', ar: 'محمد أحمد' }, registered: '2024-01-15' },
    { id: 2, code: 'B-202', icon: '🏢', status: 'available',
      address: { en: 'Maadi, Cairo', ar: 'المعادي، القاهرة' },
      price: 3200000, type: 'sale', beds: 4, baths: 3,
      finish: { en: 'Core & shell', ar: 'خام' }, unit: { en: 'Apt 2', ar: 'شقة 2' },
      agent: { en: 'F. Mahmoud', ar: 'فاطمة محمود' }, registered: '2024-02-10' },
    { id: 3, code: 'C-303', icon: '🏘️', status: 'sold',
      address: { en: 'Nile Corniche, Cairo', ar: 'النيل، القاهرة' },
      price: 1800000, type: 'sale', beds: 2, baths: 1,
      finish: { en: 'Classic', ar: 'كلاسيكي' }, unit: { en: 'Apt 3', ar: 'شقة 3' },
      agent: { en: 'A. Khalil', ar: 'علي خليل' }, registered: '2023-11-20' },
    { id: 4, code: 'D-404', icon: '🏙️', status: 'rented',
      address: { en: 'Rehab City, Cairo', ar: 'الرحاب، القاهرة' },
      price: 45000, type: 'rent', beds: 3, baths: 2,
      finish: { en: 'Modern', ar: 'حديث' }, unit: { en: 'Apt 4', ar: 'شقة 4' },
      agent: { en: 'S. Ali', ar: 'سارة علي' }, registered: '2024-03-01' },
  ],
  t: {
    en: {
      dir: 'ltr', brand: 'Ring Roads', dashboard: 'Dashboard', commission: 'Commission',
      subtitleDash: 'Property portfolio', subtitleComm: 'Calculate commissions with ease',
      total: 'Total', available: 'Available', forSale: 'For sale',
      beds: 'Beds', baths: 'Baths', type: 'Type', finish: 'Finish',
      unit: 'Unit', agent: 'Agent', registered: 'Registered',
      sale: 'Sale', rent: 'Rent', month: '/mo', currency: 'EGP',
      statusAvailable: 'Available', statusSold: 'Sold', statusRented: 'Rented',
      amounts: 'Transaction amounts', percents: 'Commission rates', results: 'Results',
      buyerAmount: 'Buyer amount', sellerAmount: 'Seller amount',
      buyerAgent: 'Buyer agent', sellerAgent: 'Seller agent', inspection: 'Inspection', manager: 'Deal manager',
      txnTotal: 'Transaction total', totalComm: 'Total commission',
    },
    ar: {
      dir: 'rtl', brand: 'رينج رودز', dashboard: 'العقارات', commission: 'العمولات',
      subtitleDash: 'لوحة العقارات', subtitleComm: 'احسب العمولات بسهولة',
      total: 'إجمالي', available: 'متاح', forSale: 'للبيع',
      beds: 'غرف', baths: 'حمام', type: 'نوع', finish: 'تشطيب',
      unit: 'الوحدة', agent: 'الوكيل', registered: 'التسجيل',
      sale: 'بيع', rent: 'إيجار', month: '/شهر', currency: 'جنيه',
      statusAvailable: 'متاح', statusSold: 'مباع', statusRented: 'مؤجر',
      amounts: 'مبالغ المعاملة', percents: 'النسب المئوية', results: 'النتائج',
      buyerAmount: 'مبلغ المشتري', sellerAmount: 'مبلغ البائع',
      buyerAgent: 'وكيل المشتري', sellerAgent: 'وكيل البائع', inspection: 'الفحص', manager: 'مدير الصفقة',
      txnTotal: 'إجمالي المعاملة', totalComm: 'إجمالي العمولات',
    },
  },
  fmt(n) { return n.toLocaleString('en-US'); },
};
